### ISSUE TITLE
NestJS v11 `@nestjs/platform-fastify` has wrong dependency

### ISSUE THREAD

**Issue by samchon** [nestjs/nest#14450]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When install NestJS v11 with `@nestjs/platform-fastify`, it tries to install `@nestjs/core@10.0.0`, and fails by dependency confliction.

The problem comes from the `@nestjs/platform-fastify`'s `package.json` file. Looking at the `package.json` file of Github repository, there is no problem. However, if I install it through `npm install --force` option and open the `package.json` file from the `node_modules/@nestjs/platform-fastify/package.json` file, its actual `peerDependencies` has a critical problem, depending on the previous major version like below.

Here is the Github repository's `peerDependencies`. As you can see, it is proper.

https://github.com/nestjs/nest/blob/e63a2c1f7c5c552c7cfb0af43500e02780087e8e/packages/platform-fastify/package.json#L29-L34

However, the NPM published `peerDependencies` is not proper. It requires previous major version of `@nestjs/core`.

```json
{
  "peerDependencies": {
    "@fastify/static": "^8.0.0",
    "@fastify/view": "^10.0.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0"
  }
}
```

### Minimum reproduction code

https://github.com/samchon/nestjs-v11-platform-fastify-dependency-bug

### Steps to reproduce

```bash
git clone https://github.com/samchon/nestjs-v11-app-use-fastify-multer-bug
npm install
npm run build

# WORKING PROPERLY
npm run setup:v10
npm run test

# ERROR OCCURES
npm run setup:v11
npm run test
```

### Expected behavior

This bug caused by wrong-publishing.

The `peerDependencies` archived in the Github repository is proper, but NPM module is not proper.

Therefore, `@nestjs/platform-fastify` must be re-published.

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [x] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

11.0.1

### Packages versions

```json
{
  "@nestjs/common": "^11.0.11",
  "@nestjs/core": "^11.0.1",
  "@nestjs/platform-fastify": "^11.0.1"
}
```

### Node.js version

20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by Tony133** [comment]
It was fixed after the release of version `11.0.1`, see the other problem here: https://github.com/nestjs/nest/issues/14437 and the PR with the fix here: https://github.com/nestjs/nest/pull/14436

I am also waiting for a new release 🔥

**Comment by tejastn10** [comment]
Hi,

I tried updating the version to `11.0.1` as suggested, but I am still facing the issue. I updated all my dependencies to the latest versions, and the error persists. Here’s the error I am encountering:

```bash
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@”^10.0.0” from @nestjs/platform-fastify@11.0.1
npm ERR! node_modules/@nestjs/platform-fastify
```

It seems that `@nestjs/platform-fastify@11.0.1` is still referencing `@nestjs/common@"^10.0.0"` as a peer dependency, even though it should support `^11.0.0`.

I also confirmed that my `package.json` dependencies are updated as follows:
```json
{
  "@nestjs/common": "^11.0.11",
  "@nestjs/core": "^11.0.1",
  "@nestjs/platform-fastify": "^11.0.1"
}
```


However, the issue still occurs during installation. It looks like the fix mentioned in #14436 hasn’t been reflected in the published package yet. Could you confirm if the fix is included in the latest release, or if there’s a timeline for a corrected version to be published?

Thank you for your assistance!

**Comment by shvamabps** [comment]
it is same for express one too right.

**Comment by kakasoo** [comment]
Yes, `@nestjs/platform-express` too.

**Comment by shvamabps** [comment]
> Yes, `@nestjs/platform-express` too.
I think the json is a bit short in the description. 
I think this is the entire json for `@nestjs/platform-express`

```json
"dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^5.0.0",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "eslint": "^8.0.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
```

Here, in the scaffold, the eslint configuration is also outdated. If possible, some ci tools like `husky` & `commitlint` integrated before hand could be a great help. It would save a lot of time and would make the development ci faster, making code and commits formatted in a certain manner, and autocompletion for environment variables where `@nestjs/config` is pre-installed and configured for the production ready application.

**Comment by Tony133** [comment]
> However, the issue still occurs during installation. It looks like the fix mentioned in [#14436](https://github.com/nestjs/nest/pull/14436) hasn’t been reflected in the published package yet. Could you confirm if the fix is included in the latest release, or if there’s a timeline for a corrected version to be published?


As soon as Kamil publishes a new version and the problem should be fixed, I think this week everything should be ready and then you can upgrade to v11.  It still takes some patience 💪

**Comment by kamilmysliwiec** [comment]
Fixed in v11.0.2
