### ISSUE TITLE
Bad Stack Traces for Http Exceptions

### ISSUE THREAD

**Issue by lhrolim** [nestjs/nest#1626]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
I am experiencing bad stack trace messages when using high level Http Exceptions provided by nestjs/commons.

For ex, the following code:

```
throw new NotFoundException(`entity ${id} not found on the database`)
```

Prints the following stack trace:

```
Error: [object Object] (Most recent call first)
at EssayApplicationService.<anonymous> (/var/app/current/dist/features/application/services/EssayApplicationService.js line 114 col 23)
111            if (essayApplication.status !== ApplicationStatus_1.ApplicationStatus.INITIATED) {
112                const EssayMsg = `Não é possível finalizar a redação ${id} pois ela encontra-se em ${essayApplication.status}`;
113                this.logger.warn(EssayMsg);
114                throw new common_1.UnprocessableEntityException(EssayMsg);
115            }
116            essayApplication.title = essayFinishData.title;
117            essayApplication.body = essayFinishData.body;
at Generator.next (<anonymous> line (unknown))
at fulfilled (/var/app/current/dist/features/application/services/EssayApplicationService.js line 16 col 58)
function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
at process._tickCallback (internal/process/next_tick.js line 68 col 7)
```

If instead I choose:

```
throw new HttpException(`essay ${id} not found on the database`, 404);
```

I get the correct stack trace:

```
Error: essay 2 not found on the database (Most recent call first)
at EssayApplicationService.validateEssayBelongsToUser (/media/luiz/b982863d-4ef7-42b3-b93a-c6bb3969e341/workspace/nota-quero-api/src/features/application/services/EssayApplicationService.ts line 128 col 19)
const err = new HttpException(`essay ${id} not found on the database`, 404);
at EssayApplicationService.<anonymous> (/media/luiz/b982863d-4ef7-42b3-b93a-c6bb3969e341/workspace/nota-quero-api/src/features/application/services/EssayApplicationService.ts line 98 col 10)
this.validateEssayBelongsToUser(essayApplication, id, currentUser)
at Generator.next (<anonymous> line (unknown))
at fulfilled (/media/luiz/b982863d-4ef7-42b3-b93a-c6bb3969e341/workspace/nota-quero-api/src/features/application/services/EssayApplicationService.ts line 16 col 58)
13import { BadRequestException, GoneException, HttpException, Injectable, UnauthorizedException, UnprocessableEntityException } from '@nestjs/common';
14import { InjectRepository } from '@nestjs/typeorm';
15import { Guid } from 'guid-typescript';
16import { EntityManager, Repository, Transaction, TransactionManager } from 'typeorm';
17import { ApplicationStatus } from '../domain/internal/ApplicationStatus';
18
19@Injectable()
at process._tickCallback (internal/process/next_tick.js line 68 col 7)
```

## Expected behavior
The correct stack trace needs to be shown

## Minimal reproduction of the problem with instructions
I believe this would happen on any environment, but let me know if a simple repository is needed

## What is the motivation / use case for changing the behavior?
This screws any sort of online error tracking since Rollbar which I'm currently using.

## Environment

<pre><code>
Nest version: 5.7.3

 
For Tooling issues:
- Node version: 10.13.0
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by lhrolim** [comment]
Thanks @blackandcode 

Any chances to reopen this one @kamilmysliwiec  ?

**Comment by kamilmysliwiec** [comment]
See this https://github.com/nestjs/nest/pull/1970

**Comment by lhrolim** [comment]
Thanks @kamilmysliwiec!

Will update my dependencies here.

**Comment by lhrolim** [comment]
@kamilmysliwiec 

Actually, I realized that we are still experiencing these issues for Guards, 403 forbidden exceptions

I suspect it might be handled at:
https://github.com/nestjs/nest/pull/2512

are there any predictions for this particular pull request to be merged ?

Thanks

**Comment by csidell-earny** [comment]
I hope this week!

**Comment by csidell-earny** [comment]
@patrickhousley Was released in 6.5.0, unfortunately if you rely on microservices there was a regression in 6.4.1

**Comment by kamilmysliwiec** [comment]
Fixed in 6.5.0. I'll look at 6.4.1 issue asap

**Comment by lhrolim** [comment]
@csidell-earny @kamilmysliwiec 

I'm still experiencing these at 6.5.2.

However it seems to happen only for `Forbidden` exceptions at `Guards` now.

**Comment by csidell-earny** [comment]
Odd, I them in the auth guard as well and they work fine. I'm take a look when I have time

**Comment by lhrolim** [comment]
@csidell-earny @kamilmysliwiec  , please disregard my previous comment.

I got that as a first impression since I was catching those at Rollbar.

After debugging a bit, I got it a bit cleaner:

Now it's still missing to handle correctly the `stack` property of the error Object.

The message and response properties are looking good though

**Comment by lhrolim** [comment]
Put up a PR that solves it.  Hope it helps!
