### ISSUE TITLE
Error typings on "applyDecorators()" with class-validator

### ISSUE THREAD

**Issue by Dominic-Preap** [nestjs/nest#3569]
## Current behavior

With #3104,  `applyDecorators` function has error typing when using combine with `class-validator` in DTO class.
```
Argument of type '(object: Object, propertyName: string) => void' is not assignable to parameter of type 'ClassDecorator | MethodDecorator'.
  Type '(object: Object, propertyName: string) => void' is not assignable to type 'ClassDecorator'.ts(2345)
```
## Input Code

What I am using before
```ts
export const IsNotEmptyString = () => {
  return (target: any, key: string) => {
    IsNotEmpty()(target, key);
    IsString()(target, key);
    ApiProperty()(target, key);
  };
};
```
When using applyDecorators 
```ts
export const IsNotEmptyString = () =>
  applyDecorators(    
    IsNotEmpty(),  // <-- use `as any` to bypass the error for now.
    IsString(), // <-- use `as any` to bypass the error for now.
    ApiProperty()
  );

```

```ts
export class LoginBody {
  @IsNotEmptyString()
  readonly username!: string;

  @IsNotEmptyString()
  readonly password!: string;
}
```

## Environment

<pre><code>
Nest version: 6.10.7
 
For Tooling issues:
- Node version: 10.15.3
- Platform:  Windows 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 6.10.8. Thanks for reporting!

**Comment by Dominic-Preap** [comment]
cc @kamilmysliwiec 
I am still having the same issue there on version 6.10.14.

```ts
export const IsOptionalDateString = () => 
applyDecorators(
  IsOptional(), // <-- still having the same issue here
  IsDateString(),  // <-- still having the same issue here
  ApiPropertyOptional());
```
![image](https://user-images.githubusercontent.com/14802170/72585261-4ab0fa00-38e5-11ea-8599-0358c574b89a.png)

Because `PropertyDecorator` cannot resolve typing in class-validator
- `IsOptional` return `(target: Object, propertyKey: string) => void` 
- `PropertyDecorator` return `(target: Object, propertyKey: string | symbol) => void`

But if I add a type like below and put it into `applyDecorators`, it'll work as expected.
` type PropertyDecorator2 = (target: Object, propertyKey: string) => void`

![image](https://user-images.githubusercontent.com/14802170/72585392-d75bb800-38e5-11ea-957c-eb48a7422ac5.png)
