### ISSUE TITLE
Fastify CORS not working

### ISSUE THREAD

**Issue by vrxj81** [nestjs/nest#3939]
## Regression

Fastify CORS not working after running `nest update`.

```ts
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, NestFastifyApplication} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';
import * as fmp from 'fastify-multipart';

(async function bootstrap() {
  const fAdapt = new FastifyAdapter();
  fAdapt.register(fmp);
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    fAdapt,
  );
  app.setGlobalPrefix('api');
  app.enableCors();
  await app.listen(+process.env.PORT || 3000, '0.0.0.0');
})();
```

**Comment by oznu** [comment]
I've encountered this issue as well.

```
  app.enableCors({
    origin: ['http://localhost:8080', 'http://localhost:4200'],
  });
```

**Comment by kamilmysliwiec** [comment]
This should be fixed in 6.11.2 @oznu @vrxj81. Let me know if you face any issues

**Comment by vrxj81** [comment]
Confirmed fixed! Thanks @kamilmysliwiec

**Comment by bamandine** [comment]
I still have this bug after an update in 6.11.5 and 6.11.7 with this configuration : 

```
app.enableCors({
    origin: ['http://localhost:8080', 'http://localhost:4200'],
});
```

The "Access-Control-Allow-Origin" header is not present. It works with a single value, but not with an array.
