### ISSUE TITLE
Nest is showing warnings when using node v14.1.0

### ISSUE THREAD

**Issue by benyou1969** [nestjs/nest#4723]
I've installed `nest.js` on fresh macOS machine and when I use yarn to start I get these warnings!

> yarn run start

```zsh
yarn run v1.22.4
$ nest start
(node:6099) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6099) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:6099) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
[Nest] 6100   - 05/03/2020, 7:05:37 PM   [NestFactory] Starting Nest application...
[Nest] 6100   - 05/03/2020, 7:05:37 PM   [InstanceLoader] AppModule dependencies initialized +15ms
[Nest] 6100   - 05/03/2020, 7:05:37 PM   [RoutesResolver] AppController {}: +7ms
[Nest] 6100   - 05/03/2020, 7:05:37 PM   [RouterExplorer] Mapped {, GET} route +4ms
[Nest] 6100   - 05/03/2020, 7:05:37 PM   [NestApplication] Nest application successfully started +3ms
```

- node: v14.1.0
- yarn: v1.22.4
- tsc:  v3.8.3
- nest: v7.1.4

The question is how can I get ride of these warnings?

**Note:** when I downgrade to `node@12`
It works fine without showing these warnings.

<img width="569" alt="Screen Shot 2020-05-03 at 7 34 41 PM" src="https://user-images.githubusercontent.com/31636863/80922537-baa09e80-8d75-11ea-9e40-f69733a93022.png">

**Comment by adelsagemilang** [comment]
Same issue here ```node v14.0.0```

**Comment by kamilmysliwiec** [comment]
Fixed in `@nestjs/cli@7.1.5`

**Comment by adelsagemilang** [comment]
still having these warnings after upgrading ```@nestjs/cli@7.1.5```

> $ nest info

```
 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Catalina
NodeJS Version : v14.0.0
(node:17895) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17895) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:17895) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
NPM Version    : 6.14.4

[Nest CLI]
Nest CLI Version : 7.1.5

[Nest Platform Information]
platform-express version : 7.0.9
mongoose version         : 6.4.0
typeorm version          : 7.0.0
common version           : 7.0.9
config version           : 0.4.0
core version             : 7.0.9

**Comment by benyou1969** [comment]
> @kamilmysliwiec
> still getting these warnings after upgrade `@nestjs/cli@7.1.5`
> 
> > $ nest info
> 
> ```
>  _   _             _      ___  _____  _____  _     _____
> | \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
> |  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
> | . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
> | |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
> \_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/
> 
> 
> [System Information]
> OS Version     : macOS Catalina
> NodeJS Version : v14.0.0
> (node:17895) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:17895) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
> (node:17895) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
> NPM Version    : 6.14.4
> 
> [Nest CLI]
> Nest CLI Version : 7.1.5
> 
> [Nest Platform Information]
> platform-express version : 7.0.9
> mongoose version         : 6.4.0
> typeorm version          : 7.0.0
> common version           : 7.0.9
> config version           : 0.4.0
> core version             : 7.0.9
> ```

for me it's working after I updated `nest/cli` globally, 
try to update it in your `package.json`
Note: you are using node: `14`, the issue here was in `v14.1.0`

Hope this helps!.
