### ISSUE TITLE
E2E Testing  in a Graphql app

### ISSUE THREAD

**Issue by codeback** [nestjs/nest#484]
I'm having errors testing my Graphql API with jest. I've followed the example described [here](https://docs.nestjs.com/fundamentals/e2e-testing).

The app works fine, but when I run e2e tests, it fails.

Error
```
TypeError: Cannot convert undefined or null to object
        at Function.getPrototypeOf (<anonymous>)

      10 |   createSchema() {
      11 |     const typeDefs = this.graphQLFactory.mergeTypesByPaths('../**/*.graphql');
    > 12 |     const schema = this.graphQLFactory.createSchema({ typeDefs });
      13 |     return schema;
      14 |   }
      15 | }

```

AppModule
```
import {
  Module
} from '@nestjs/common';
import { GraphQLHelperModule } from './graphql/index';
import { ProductModule } from './product/index';

@Module({
  imports: [ProductModule, GraphQLHelperModule],
})
export class ApplicationModule {}
```

GraphQLService
```
import { Component } from '@nestjs/common';
import { GraphQLFactory } from '@nestjs/graphql';

@Component()
export class GraphQLService {
  constructor(
    private readonly graphQLFactory: GraphQLFactory,
  ) {}

  createSchema() {
    const typeDefs = this.graphQLFactory.mergeTypesByPaths('../**/*.graphql');
    const schema = this.graphQLFactory.createSchema({ typeDefs });
    return schema;
  }
}
```

GraphQLModule
```
import {
  Module,
  MiddlewaresConsumer,
  NestModule,
  RequestMethod
} from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { graphqlExpress, graphiqlExpress } from 'apollo-server-express';
import { GraphQLService } from './graphql.service';

@Module({
  imports: [GraphQLModule],
  components: [GraphQLService]
})
export class GraphQLHelperModule implements NestModule {
  constructor(
    private readonly graphQLService: GraphQLService,
  ) {}

  configure(consumer: MiddlewaresConsumer) {
    const schema = this.graphQLService.createSchema();

    consumer
      .apply(
        graphiqlExpress({
          endpointURL: '/graphql'
        }),
      )
      .forRoutes({ path: '/graphiql', method: RequestMethod.GET })
      .apply(graphqlExpress(req => ({ schema, rootValue: req })))
      .forRoutes({ path: '/graphql', method: RequestMethod.ALL });
  }
}
```

Finally my test
```
import * as express from 'express';
import { GraphQL } from 'graphql';
import { tester } from 'graphql-tester';
import { Test } from '@nestjs/testing';
import { GraphQLModule } from '@nestjs/graphql';
import * as chai from 'chai';
import * as chaiAsPromised from 'chai-as-promised';
import { create as createExpressWrapper } from './express-wrapper';
import { ProductModule, ProductService } from '../src/product/index';
import { GraphQLHelperModule, GraphQLService } from '../src/graphql/index';

chai.should();
chai.use(chaiAsPromised);

describe('Product', () => {
  const server = express();
  const productService = { findAll: () => ['test'] };

  beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [GraphQLHelperModule, ProductModule]
    })
      .overrideComponent(ProductService).useValue(productService)
      .compile();

    const app = module.createNestApplication(server);
    await app.init();

    const graphQLService = module.get<GraphQLService>(GraphQLService);
    server.use('/graphql', GraphQL({
      schema: graphQLService.createSchema()
    }));

  });

  describe('Query getProduct', () => {

    const gql = tester({
      server: createExpressWrapper(server),
      url: '/graphql',
      // authorization: `Bearer ${token}`,
      contentType: 'application/json'
    });

    const response = gql('{getProduct(id:1)}');

    response.then(data => console.log(data));

    it('Returns success', () => {
      return response.should.eventually.have.property('success').equal(true);
    });

    it('Returns the correct Status code', () => {
      return response.should.eventually.have.property('status').equal(200);
    });
  });
});
```
Anyone can tell me what I am doing wrong? 
Thanks in advance

**Comment by unlight** [comment]
looks like I got same error #488

**Comment by kamilmysliwiec** [comment]
Thanks for reporting, I'm on it. 💪

**Comment by kamilmysliwiec** [comment]
Fixed in `v4.6.6` 🙂

**Comment by mnlttt** [comment]
I'm still getting this error :-/

```
"@nestjs/common": "^4.6.6",
"@nestjs/core": "^4.6.6",
"@nestjs/graphql": "^2.0.0",
```

It happens as soon as I import `SubscriptionsModule.forRoot()` and copy/paste what's inside _subscription_ folder and _app.module.ts_ from [GraphQL Apollo example](https://github.com/nestjs/nest/tree/master/examples/12-graphql-apollo)

**Comment by DanielKucal** [comment]
@mnlttt, have you resolved it?

**Comment by mnlttt** [comment]
@DanielKucal IIRC (and I could be wrong), I solved passing an instance of an Express's `http` rather than NodeJS's in `subscription.providers.ts`, but remember, I could be wrong and I cannot verify, sorry!

**Comment by Xample** [comment]
A very simple approach for e2e test is as follow:
```ts
import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import * as request from 'supertest';
import { AppModule } from '../src/app.module';

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/ (GET)', () => {
    return request(app.getHttpServer())
      .post('/graphql')
      .send({
        operationName: null,
        variables: {},
        query: '{getProducts{id, price}}',
      })
      .expect(200);
  });
});
```

**Comment by Xample** [comment]
And here is the way to use it in a "typed way", using apollo-codegen you can of course type the result and the variables. Also adding an `index.d.ts` with
```ts
declare module '*.graphql' {
    import { DocumentNode } from 'graphql';
    const value: DocumentNode;
    export { value } ;
    export default value;
}
```
Will allow importing the queries directly, instead of inlining using: 
```
gql`your query`
```

```ts
import { INestApplication } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { Test, TestingModule } from '@nestjs/testing';
import { ApolloServerTestClient, createTestClient } from 'apollo-server-testing';
import gql from 'graphql-tag';
import { AppModule } from '../src/app.module';

describe('AppController (e2e)', () => {
  let app: INestApplication;
  let apolloClient: ApolloServerTestClient;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();

    const module: GraphQLModule = moduleFixture.get<GraphQLModule>(GraphQLModule);
    apolloClient = createTestClient((module as any).apolloServer);

  });

  it('Should be able to use apolloClientTest', async () => {
    const { query } = apolloClient;
    const result: any = await query({
      query: gql`query {
          getProducts {
              name
              id
          }
      }`,
      variables: {},
    });
    console.log(result);
    // test whatever you want to test here
  });
});
```
